version: '3.3'

services:
  postgres:
    container_name: reva-datawarehouse-postgres
    image: 'postgres:11.0-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reva-datawarehouse
    ports:
      - "5432:5433"