"""Add CandidacyCandidacyStatus table

Revision ID: 864a3ccf24b8
Revises: 4969db06ce05
Create Date: 2022-05-30 17:32:36.027020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '864a3ccf24b8'
down_revision = '4969db06ce05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidacy_candidacy_status',
                    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('candidacy_id', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('status', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidacy_candidacy_status')
    # ### end Alembic commands ###
