"""First tables goal and candidacy

Revision ID: 24366e4217ee
Revises:
Create Date: 2022-05-27 11:37:53.716784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24366e4217ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidacy',
                    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('deviceId', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('keycloak_sub', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('companion_id', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('certification_id', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('phone', sa.VARCHAR(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('goal',
                    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('label', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('needs_additional_information', sa.BOOLEAN(), nullable=True),
                    sa.Column('order', sa.INTEGER(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal')
    op.drop_table('candidacy')
    # ### end Alembic commands ###
