"""Add CandidacyGoal table

Revision ID: 4969db06ce05
Revises: 24366e4217ee
Create Date: 2022-05-30 17:21:32.507136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4969db06ce05'
down_revision = '24366e4217ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidacy_goal',
                    sa.Column('candidacy_id', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('goal_id', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('additional_information', sa.TEXT(), nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('candidacy_id', 'goal_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidacy_goal')
    # ### end Alembic commands ###
