"""Add Experience table

Revision ID: cea7434f43b1
Revises: 864a3ccf24b8
Create Date: 2022-05-30 17:43:16.745293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cea7434f43b1'
down_revision = '864a3ccf24b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience',
                    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('description', sa.TEXT(), nullable=True),
                    sa.Column('startedAt', postgresql.TIMESTAMP(), nullable=True),
                    sa.Column('candidacy_id', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('duration', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('title', sa.TEXT(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience')
    # ### end Alembic commands ###
